libbpf-cargo: Handle empty unions in BTF types
This was noticed because a "vmlinux.h" contained:

struct bio {
...
	union {};
...
};

Which caused the following error when trying to use "struct bio" in a
.bpf.c file:

  thread 'main' panicked at /home/jrc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libbpf-cargo-0.24.6/src/gen/btf.rs:769:49:
  index out of bounds: the len is 0 but the index is 0

Fix this by hiding empty unions from the generated types. Rust does not
allow union types with zero fields.

Signed-off-by: Joel Colledge <joel.colledge@linbit.com>