libbpf-cargo: Report proper error chain on missing object file
An error message such as
> Error: Failed to generate skeleton for libbpf-rs/examples/runqslower/src/bpf/runqslower.bpf.c
>
> Caused by:
>     No such file or directory (os error 2)

is misleading and nonsensical, given that runqslower.bpf.c exists.
Report a proper causal chain to make errors like this at least somewhat
actionable.

Signed-off-by: Daniel Müller <deso@posteo.net>