libbpf-cargo/btf: Don't use _ pattern in match arm
Let's explicitly list all enums in match arms, so that
when we add a new BtfKind/BtfType, we can't forget to
update those pattern matches because rust will complain
about `error[E0004]: non-exhaustive patterns`.

Signed-off-by: Hengqi Chen <chenhengqi@outlook.com>