Allow having package.metadata sections that aren't for libbpf
This allows having sections of the following form in Cargo.toml:
```
[package.metadata.deb]
 # ...
```

Previously, they would give a hard error:

```
$ cargo libbpf make
Compiling BPF objects
Error: Failed to compile BPF objects

Caused by:
    Failed to process package=bpf-graceful-restart, error=unknown variant `deb`, expected `libbpf`
```

Serde by default requires all enum variants to be known ahead of time;
this works by changing the deserialized type to a struct instead.

Signed-off-by: Joshua Nelson <jnelson@cloudflare.com>