Specify libbpf-rs version in libbpf-cargo/Cargo.toml
libbpf-cargo fails to publish because of:
> error: all dependencies must have a version specified when publishing.
> dependency `libbpf-rs` does not specify a version
> Note: The published dependency will use the version from crates.io,
> the `path` specification will be removed from the dependency declaration.

Hence, explicitly specify the version to use. Also bump the recommended
versions to use in the README.

Signed-off-by: Daniel Müller <deso@posteo.net>